#!/bin/bash


huaweiLinkNameStartsWith="wwp0s"

huaweiLinkName=$(eval ifconfig -a | grep -i $huaweiLinkNameStartsWith | awk '{print $1}' | sed 's/Link//')

filterDeviceCommand="lsusb | grep -i huawei"

huaweiDevice=$(eval $filterDeviceCommand)

deviceId=$(eval $filterDeviceCommand | awk '{print $6}')

vendorId=$(eval echo $deviceId | awk -F ':' '{print $1}')
productId=$(eval echo $deviceId | awk -F ':' '{print $2}')

clear
echo ""
echo "Device Found"
echo "***************"
echo $huaweiDevice
echo "***************"


echo ""
echo "Extracted Device ID Is"
echo "***************"
echo $deviceId
echo "***************"

echo ""
echo "Separated Device Vendor And Product ID Are"
echo "***************"
echo "Device Vendor ID is [" $vendorId "]"
echo "Device Product ID is [" $productId "]"
echo "***************"

echo ""
echo "Switching Device to [NetworkCard] Mode"
echo "***************"
switchToNetworkModeCommand=$(eval usb_modeswitch -v $vendorId -p $productId -J)
echo "***************"

echo ""
echo "*****Enabling Netork Interface**********"
enableHuaweiLANLink=$(eval ip link set $huaweiLinkName up)
echo "*****Enabling DHCP***********"
enableDHCPOnHuaweiLANLink=$(eval dhclient $huaweiLinkName)
echo "***************"

echo "********Securing DNS*********"
echo "Making sure Huawei is unable to update resolv.conf"
sudo cp /etc/resolv.conf /etc/backup_resolv_dot_conf
echo "Original /etc/resolv.conf saved as /etc/backup_resolv_dot_conf"
sudo chattr -i /etc/resolv.conf
sudo rm /etc/resolv.conf
sudo touch /etc/resolv.conf
sudo chmod 644 /etc/resolv.conf
echo "Setting Cloudflare as default DNS"
sudo echo "nameserver 1.1.1.1" > /etc/resolv.conf
sudo echo "nameserver 1.0.0.1" >> /etc/resolv.conf
echo "Making sure other softwares are unable to update resolv.conf"
sudo chmod 444 /etc/resolv.conf
sudo chattr +i /etc/resolv.conf
echo "******************************"


echo ""
echo "***************"
echo "Internet should be working now"
echo "If not then"
echo "Run"
echo "ifconfig -a"
echo "Check output to see Huawei link name"
echo "Change huaweiLinkNameStartsWith variable on top"
echo "As per ifconfig -a output on your PC"
echo "***************"
